### ISSUE TITLE
Некорректно работает тултип в DatePicker

### ISSUE THREAD

**Issue by mshatikhin** [skbkontur/react-ui-validations#19]
Не появляется тултип валидации по ховеру
![1515994346649](https://user-images.githubusercontent.com/1788385/34928598-83a86442-f9e0-11e7-8ff0-3550f827f566.png)

По фокусу появляется, но перекрывает сам DatePicker

![1515993948651](https://user-images.githubusercontent.com/1788385/34928609-922dbfda-f9e0-11e7-8f04-a10a2d6c4e5e.png)

версии либ:
"@skbkontur/react-ui": "0.10.8",
"react-ui-validations": "0.2.13"

**Comment by tihonove** [comment]
Ховер надо починить в retail-ui: https://github.com/skbkontur/retail-ui/issues/392

**Comment by tihonove** [comment]
Тултип поверх дейтпикера починен тут: https://github.com/skbkontur/retail-ui/commit/8ea6a248e2dd166de471c1cbef5f920ad456cb94

Надо обновиться до retail-ui@0.10.9

**Comment by wKich** [comment]
Та же проблема с `z-index` https://github.com/skbkontur/retail-ui/issues/776. Закрываю, решение можно отслеживать в связанной задаче
