### ISSUE TITLE
ValidationContainer, не скролит к элементу если он под fixed плашкой но во вьюпорте.

### ISSUE THREAD

**Issue by mshatikhin** [skbkontur/react-ui-validations#31]
ValidationContainer, при заданном scrollOffset, не скролит к элементу если он под fixed плашкой но во вьюпорте.

![scrolloffset](https://user-images.githubusercontent.com/1788385/44788298-15eab880-abb3-11e8-9f7b-c0a7dfd348a2.gif)

**Comment by wKich** [comment]
Похоже на дубль https://github.com/skbkontur/retail-ui/issues/1250. Закрываю
