### ISSUE TITLE
children.focus()

### ISSUE THREAD

**Issue by Frumcheg** [skbkontur/react-ui-validations#9]
Как видно из кода: https://github.com/skbkontur/react-ui-validations/blob/master/src/Behaviour/ValidationWrapper.jsx#L179,
скрол до невалидного элемента произойдет, если у него есть метод `focus`. Бывает, что нужно показать ошибку на элементе, у которого нет такого метода. Можно ли убрать ту проверку в коде? Тем более, что ниже есть еще одна такая же https://github.com/skbkontur/react-ui-validations/blob/master/src/Behaviour/ValidationWrapper.jsx#L186

**Comment by tihonove** [comment]
Да, норм. Давай

**Comment by tihonove** [comment]
FIxed in v0.2.5
